### ISSUE TITLE
failed to select a version for the requirement time 

### ISSUE THREAD

**Issue by liyichao** [borntyping/rust-simple_logger#72] opened 2023-01-16 11:35 UTC
error: failed to select a version for the requirement `time = "^0.3.16"`
candidate versions found which didn't match: 0.3.15, 0.3.14, 0.3.13, ...
location searched: `ustc` index (which is replacing registry `crates-io`)
required by package `simple_logger v4.0.0`
    ... which satisfies dependency `simple_logger = "^4.0"` (locked to 4.0.0) of package `xxx`
perhaps a crate was updated and forgotten to be re-vendored?

**Comment by borntyping** [comment] 2023-01-16 12:49
`time@0.3.16` is definitely availible on crates.io: https://crates.io/crates/time/0.3.16

This might be a problem with the alternative index you are using. If I'm looking at the right index, it does appear to exist on that index: https://mirrors.ustc.edu.cn/crates.io-index/ti/me/time (this file contains a description of version 0.3.16).

**Comment by borntyping** [comment] 2023-08-16 22:48
Closing this — can't reproduce and it doesn't seem to be a problem with `simpler_logger`.

**Closed by borntyping** 2023-08-16 22:48 UTC
