### ISSUE TITLE
no colors when using feature stderr and redirecting stdout

### ISSUE THREAD

**Issue by andbleo** [borntyping/rust-simple_logger#71] opened 2022-12-22 19:02 UTC
When I have the stderr and colors features enabled and redirect just stdout, the colors in my stderr logs are no longer there.  If I remove the stderr feature and try redirecting stderr, my stdout logs do have color.  Is this expected behavior?

This is on macOS and happens in both iTerm2 and the vs code terminal.

Here is how I pull in simple_logger in Cargo.toml: `simple_logger = { version = "4.0.0", features = ["stderr"] }`

**Comment by borntyping** [comment] 2022-12-22 20:10
I don't think this is expected. I can't see any reason this would happen - the `colors` and `stderr` features are pretty separate. Do you get coloured logs if you enable `colors` _and_ `stderr` without redirecting any output?

I can see a potential bug in the code where this might happen on Windows specifically: https://github.com/borntyping/rust-simple_logger/blob/main/src/lib.rs#L463

**Comment by andbleo** [comment] 2022-12-22 20:53
I do get colors when I don't redirect stdout.
Perhaps it is a bug in the colored dependency for non-windows platforms?

**Comment by borntyping** [comment] 2022-12-22 23:19
Ah: this does look like it may be a bug in `colored`, which checks STDOUT to decide if it should show colours.

https://docs.rs/colored/latest/src/colored/control.rs.html#108

**Comment by andbleo** [comment] 2022-12-24 21:21
I will open an issue with colored and link to this one.

**Comment by borntyping** [comment] 2023-08-16 22:48
Closing this as it looks like it's currently intended behavior on `coloured`'s part.

**Closed by borntyping** 2023-08-16 22:48 UTC
